server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/jobs?useSSL=false&serverTimezone=UTC
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1011
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
